name: signal-bot
services:
    bot:
        image: ghcr.io/awkwardbunny/bot:main
        restart: always
        volumes:
            - ${PWD}/config.json:/app/config.json
            - ${PWD}/bot.log:/app/bot.log
